from __future__ import annotations

import warnings
from dataclasses import dataclass
from io import BytesIO
from uuid import UUID, uuid4

from botocore.exceptions import BotoCoreError, ClientError
from PIL import Image, UnidentifiedImageError
from sqlalchemy import func, select
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from app.core.config import settings
from app.core.storage import get_object_storage_client
from app.models.entities import Pet, PetPhoto


class InvalidPetPhotoError(Exception):
    """Raised when an uploaded file is not an accepted and safe image."""


class PetPhotoNotFoundError(Exception):
    """Raised when the pet does not exist."""


class PetPhotoStorageError(Exception):
    """Raised when MinIO cannot store or remove an object."""


class PetPhotoPersistenceError(Exception):
    """Raised when the database record cannot be persisted."""


@dataclass(frozen=True)
class ValidatedPetImage:
    """Trusted image data after server-side validation."""

    contents: bytes
    content_type: str
    extension: str


_ALLOWED_IMAGE_FORMATS: dict[str, tuple[str, str]] = {
    "JPEG": ("image/jpeg", "jpg"),
    "PNG": ("image/png", "png"),
    "WEBP": ("image/webp", "webp"),
}


def validate_pet_image(contents: bytes) -> ValidatedPetImage:
    """
    Validate the actual file bytes.

    Never trust the browser-provided filename or Content-Type header.
    Pillow identifies the true image format from the bytes themselves.
    """
    if not contents:
        raise InvalidPetPhotoError("The uploaded file is empty.")

    if len(contents) > settings.max_pet_photo_upload_bytes:
        raise InvalidPetPhotoError(
            f"An image cannot exceed {settings.max_pet_photo_upload_bytes} bytes."
        )

    try:
        # Treat decompression-bomb warnings as errors to reject images whose
        # pixel dimensions could consume excessive memory during processing.
        with warnings.catch_warnings():
            warnings.simplefilter("error", Image.DecompressionBombWarning)

            with Image.open(BytesIO(contents)) as image:
                detected_format = image.format
                image.verify()  # Verifies that the image data is structurally valid.

    except (
        UnidentifiedImageError,
        OSError,
        Image.DecompressionBombError,
        Image.DecompressionBombWarning,
    ) as error:
        raise InvalidPetPhotoError("Upload a valid JPEG, PNG, or WebP image.") from error

    if detected_format not in _ALLOWED_IMAGE_FORMATS:
        raise InvalidPetPhotoError("Only JPEG, PNG, and WebP images are supported.")

    content_type, extension = _ALLOWED_IMAGE_FORMATS[detected_format]

    return ValidatedPetImage(
        contents=contents,
        content_type=content_type,
        extension=extension,
    )


def create_pet_photo(
    database_session: Session,
    *,
    pet_id: UUID,
    shelter_id: UUID,
    image: ValidatedPetImage,
    alt_text: str,
) -> PetPhoto:
    """
    Upload an already validated image and create its PetPhoto database record.

    The object key is generated by the server; user filenames never affect
    storage paths, preventing collisions and path-manipulation attempts.
    """
    normalized_alt_text = alt_text.strip()

    if not normalized_alt_text:
        raise InvalidPetPhotoError("Alt text is required.")

    if len(normalized_alt_text) > 255:
        raise InvalidPetPhotoError("Alt text cannot exceed 255 characters.")

    # Locking the pet serializes uploads for the same pet, so two simultaneous
    # uploads do not receive the same sort_order.
    # A manager may upload photos only for pets owned by their own shelter.
    # Returning no row for another shelter avoids exposing its pet information.
    pet = database_session.scalar(
        select(Pet)
        .where(
            Pet.id == pet_id,
            Pet.shelter_id == shelter_id,
        )
        .with_for_update()
    )

    if pet is None:
        raise PetPhotoNotFoundError

    next_sort_order = database_session.scalar(
        select(func.coalesce(func.max(PetPhoto.sort_order) + 1, 0)).where(PetPhoto.pet_id == pet_id)
    )
    # SQL returns 0 for a pet with no photos. The fallback also satisfies
    # static type checking if the database driver returns None unexpectedly.
    sort_order = next_sort_order if next_sort_order is not None else 0

    # UUID-based keys are collision-resistant and do not reveal user filenames.
    object_key = f"pets/{pet.id}/photos/{uuid4().hex}.{image.extension}"

    storage_client = get_object_storage_client()

    try:
        storage_client.put_object(
            Bucket=settings.minio_bucket,
            Key=object_key,
            Body=image.contents,
            ContentType=image.content_type,
            ContentLength=len(image.contents),
        )
    except (BotoCoreError, ClientError) as error:
        raise PetPhotoStorageError("The image could not be uploaded to object storage.") from error

    photo = PetPhoto(
        pet_id=pet.id,
        object_key=object_key,
        alt_text=normalized_alt_text,
        sort_order=sort_order,
    )
    database_session.add(photo)

    try:
        database_session.commit()
        database_session.refresh(photo)
    except SQLAlchemyError as error:
        database_session.rollback()

        try:
            # If the database write fails, remove the object that was just
            # uploaded so MinIO does not accumulate unused files.
            storage_client.delete_object(
                Bucket=settings.minio_bucket,
                Key=object_key,
            )
        except (BotoCoreError, ClientError):
            # The original database error remains the useful error to expose.
            pass

        raise PetPhotoPersistenceError("The photo record could not be saved.") from error

    return photo
