from __future__ import annotations

from collections.abc import Iterator
from io import BytesIO
from types import SimpleNamespace
from typing import Any, cast
from uuid import UUID, uuid4

import pytest
from botocore.exceptions import ClientError
from fastapi.testclient import TestClient
from PIL import Image
from sqlalchemy import select
from sqlalchemy.exc import SQLAlchemyError
from sqlalchemy.orm import Session

from app.core.config import settings
from app.models.entities import PetPhoto, ShelterMember, ShelterMemberRole
from app.services import pet_photos
from app.services.pet_photos import (
    InvalidPetPhotoError,
    PetPhotoPersistenceError,
    PetPhotoStorageError,
    create_pet_photo,
)


# Auxiliary database double used to isolate service tests from PostgreSQL. It
# supplies the scalar query results expected by the service and records add,
# commit, and rollback calls so tests can verify transaction behavior.
class FakeDatabaseSession:
    def __init__(
        self,
        scalar_results: list[object | None],
        *,
        fail_commit: bool = False,
    ) -> None:
        self._scalar_results = iter(scalar_results)
        self.added_objects: list[object] = []
        self.commit_calls = 0
        self.rollback_calls = 0
        self.fail_commit = fail_commit

    def scalar(self, statement: object) -> object | None:
        del statement
        return next(self._scalar_results)

    def add(self, instance: object) -> None:
        self.added_objects.append(instance)

    def commit(self) -> None:
        self.commit_calls += 1

        if self.fail_commit:
            raise SQLAlchemyError("Simulated database failure.")

    def refresh(self, instance: object) -> None:
        del instance

    def rollback(self) -> None:
        self.rollback_calls += 1


# Auxiliary object-storage double used to isolate tests from MinIO. It records
# upload and deletion arguments, and can raise a boto3-compatible error so the
# tests cover both successful uploads and failure cleanup paths.
class FakeObjectStorageClient:
    def __init__(self) -> None:
        self.put_calls: list[dict[str, Any]] = []
        self.delete_calls: list[dict[str, Any]] = []
        self.fail_upload = False

    def put_object(self, **kwargs: Any) -> dict[str, Any]:
        if self.fail_upload:
            raise ClientError(
                {"Error": {"Code": "InternalError", "Message": "Storage failed."}},
                "PutObject",
            )

        self.put_calls.append(kwargs)
        return {}

    def delete_object(self, **kwargs: Any) -> dict[str, Any]:
        self.delete_calls.append(kwargs)
        return {}


# Auxiliary fixture that replaces the production storage client with the fake
# client for the duration of each test and automatically restores the patch.
@pytest.fixture
def fake_storage_client(
    monkeypatch: pytest.MonkeyPatch,
) -> Iterator[FakeObjectStorageClient]:
    fake_client = FakeObjectStorageClient()

    monkeypatch.setattr(
        pet_photos,
        "get_object_storage_client",
        lambda: fake_client,
    )

    yield fake_client


# Auxiliary image factory that creates valid, tiny image files in memory. The
# generated bytes let tests exercise content-based format detection without
# reading fixtures from disk or making assumptions based on file extensions.
def make_image_bytes(image_format: str = "PNG") -> bytes:
    image_buffer = BytesIO()

    with Image.new("RGB", (20, 20), color="orange") as image:
        image.save(image_buffer, format=image_format)

    return image_buffer.getvalue()


# Auxiliary API setup helper that creates a unique test user and logs them in.
# It returns both the response data and bearer token needed by photo endpoints.
def register_and_login_for_photo(
    client: TestClient,
    *,
    email: str,
    display_name: str,
) -> tuple[dict[str, Any], str]:
    """Create a user and return their data and authentication token."""
    registration_response = client.post(
        "/api/v1/users",
        json={
            "email": email,
            "password": "test-password",
            "display_name": display_name,
        },
    )

    assert registration_response.status_code == 201

    login_response = client.post(
        "/api/v1/auth/login",
        json={
            "email": email,
            "password": "test-password",
        },
    )

    assert login_response.status_code == 200

    return (
        registration_response.json(),
        login_response.json()["access_token"],
    )


# Auxiliary API setup helper that creates a shelter owned by the authenticated
# user, allowing subsequent tests to exercise shelter authorization rules.
def create_shelter_for_photo(
    client: TestClient,
    token: str,
    *,
    name: str = "Austin Animal Rescue",
    slug: str = "austin-animal-rescue",
    email: str = "photos@austinrescue.org",
) -> dict[str, Any]:
    """Create a shelter owned by the authenticated user."""
    response = client.post(
        "/api/v1/shelters",
        headers={"Authorization": f"Bearer {token}"},
        json={
            "name": name,
            "slug": slug,
            "email": email,
            "phone": "512-555-0100",
            "city": "Austin",
            "state": "TX",
        },
    )

    assert response.status_code == 201

    return response.json()


# Auxiliary API setup helper that creates a draft pet in the owner's shelter.
# The returned pet ID is used as the target for photo upload requests.
def create_pet_for_photo(
    client: TestClient,
    token: str,
) -> dict[str, Any]:
    """Create a draft pet owned by the authenticated user's shelter."""
    response = client.post(
        "/api/v1/shelter/pets",
        headers={"Authorization": f"Bearer {token}"},
        json={
            "name": "Luna",
            "species": "Dog",
            "breed": "Labrador Retriever",
            "sex": "Female",
            "birth_date": "2023-05-10",
            "size": "Large",
            "description": "Friendly and energetic.",
        },
    )

    assert response.status_code == 201

    return response.json()


# Intent: verify valid PNG bytes are accepted and normalized.
# Ensures: detected metadata matches the image content.
def test_validate_pet_image_accepts_a_valid_png() -> None:
    image_bytes = make_image_bytes("PNG")

    validated_image = pet_photos.validate_pet_image(image_bytes)

    assert validated_image.contents == image_bytes
    assert validated_image.content_type == "image/png"
    assert validated_image.extension == "png"


# Intent: verify empty uploads are rejected.
# Ensures: validation raises the domain error before storage or persistence.
def test_validate_pet_image_rejects_an_empty_file() -> None:
    with pytest.raises(InvalidPetPhotoError, match="empty"):
        pet_photos.validate_pet_image(b"")


# Intent: verify corrupted image bytes are rejected.
# Ensures: invalid content raises the domain validation error.
def test_validate_pet_image_rejects_a_corrupted_file() -> None:
    corrupted_contents = b"This is not an image."

    with pytest.raises(InvalidPetPhotoError, match="valid JPEG, PNG, or WebP"):
        pet_photos.validate_pet_image(corrupted_contents)


# Intent: verify real but unsupported image formats are rejected.
# Ensures: GIF uploads raise the domain validation error.
def test_validate_pet_image_rejects_an_unsupported_image_format() -> None:
    gif_bytes = make_image_bytes("GIF")

    with pytest.raises(InvalidPetPhotoError, match="Only JPEG, PNG, and WebP"):
        pet_photos.validate_pet_image(gif_bytes)


# Intent: verify the storage test double records uploads.
# Ensures: upload metadata is preserved without a network request.
def test_fake_storage_client_records_an_upload(
    fake_storage_client: FakeObjectStorageClient,
) -> None:
    fake_storage_client.put_object(
        Bucket="pawple-media",
        Key="pets/example/photos/example.png",
        Body=b"image bytes",
        ContentType="image/png",
    )

    assert len(fake_storage_client.put_calls) == 1
    assert fake_storage_client.put_calls[0]["Bucket"] == "pawple-media"
    assert fake_storage_client.put_calls[0]["ContentType"] == "image/png"


# Intent: verify photo creation uploads the object before persisting its record.
# Ensures: the generated key, database record, and transaction state are consistent.
def test_create_pet_photo_uploads_the_object_and_persists_the_record(
    fake_storage_client: FakeObjectStorageClient,
) -> None:
    pet_id = uuid4()
    shelter_id = uuid4()

    # Critical setup: the service first resolves the pet and next sort order.
    fake_database_session = FakeDatabaseSession(
        [
            SimpleNamespace(id=pet_id),
            0,
        ]
    )

    validated_image = pet_photos.validate_pet_image(make_image_bytes("PNG"))

    photo = create_pet_photo(
        cast(Session, fake_database_session),
        pet_id=pet_id,
        shelter_id=shelter_id,
        image=validated_image,
        alt_text="Orange dog sitting outside.",
    )

    # Critical assertion: storage uses a server-generated object key.
    assert len(fake_storage_client.put_calls) == 1
    assert fake_storage_client.put_calls[0]["Bucket"] == settings.minio_bucket
    assert fake_storage_client.put_calls[0]["ContentType"] == "image/png"
    assert fake_storage_client.put_calls[0]["Key"].startswith(f"pets/{pet_id}/photos/")

    # Critical assertion: persistence occurs only after a successful upload.
    assert fake_database_session.added_objects == [photo]
    assert fake_database_session.commit_calls == 1
    assert fake_database_session.rollback_calls == 0

    assert photo.pet_id == pet_id
    assert photo.alt_text == "Orange dog sitting outside."
    assert photo.sort_order == 0
    assert photo.object_key == fake_storage_client.put_calls[0]["Key"]


# Intent: verify storage failures prevent database writes.
# Ensures: the service raises a storage error and leaves no persisted record.
def test_create_pet_photo_returns_storage_error_when_minio_upload_fails(
    fake_storage_client: FakeObjectStorageClient,
) -> None:
    fake_storage_client.fail_upload = True

    pet_id = uuid4()
    fake_database_session = FakeDatabaseSession(
        [
            SimpleNamespace(id=pet_id),
            0,
        ]
    )

    validated_image = pet_photos.validate_pet_image(make_image_bytes("PNG"))

    with pytest.raises(PetPhotoStorageError, match="could not be uploaded"):
        create_pet_photo(
            cast(Session, fake_database_session),
            pet_id=pet_id,
            shelter_id=uuid4(),
            image=validated_image,
            alt_text="Orange dog sitting outside.",
        )

    # Critical assertion: failed uploads must not mutate the database.
    assert fake_database_session.added_objects == []
    assert fake_database_session.commit_calls == 0
    assert fake_storage_client.delete_calls == []


# Intent: verify database failures clean up an already-uploaded object.
# Ensures: the transaction rolls back and no orphaned storage object remains.
def test_create_pet_photo_deletes_the_object_when_database_commit_fails(
    fake_storage_client: FakeObjectStorageClient,
) -> None:
    pet_id = uuid4()

    fake_database_session = FakeDatabaseSession(
        [
            SimpleNamespace(id=pet_id),
            0,
        ],
        fail_commit=True,
    )

    validated_image = pet_photos.validate_pet_image(make_image_bytes("WEBP"))

    with pytest.raises(PetPhotoPersistenceError, match="could not be saved"):
        create_pet_photo(
            cast(Session, fake_database_session),
            pet_id=pet_id,
            shelter_id=uuid4(),
            image=validated_image,
            alt_text="Dog wearing a blue collar.",
        )

    # Critical assertion: the database transaction is rolled back.
    assert fake_database_session.rollback_calls == 1

    # Critical assertion: the uploaded object is removed after persistence fails.
    assert len(fake_storage_client.put_calls) == 1
    assert len(fake_storage_client.delete_calls) == 1

    uploaded_key = fake_storage_client.put_calls[0]["Key"]
    deleted_key = fake_storage_client.delete_calls[0]["Key"]

    assert deleted_key == uploaded_key
    assert fake_storage_client.delete_calls[0]["Bucket"] == settings.minio_bucket


# Intent: verify a shelter owner can upload a valid pet photo.
# Ensures: the photo is stored, persisted, and returned without exposing its object key.
def test_shelter_owner_can_upload_pet_photo(
    client: TestClient,
    database_session: Session,
    fake_storage_client: FakeObjectStorageClient,
) -> None:
    _, owner_token = register_and_login_for_photo(
        client,
        email="photo-owner@example.com",
        display_name="Photo Shelter Owner",
    )

    create_shelter_for_photo(client, owner_token)
    pet = create_pet_for_photo(client, owner_token)

    image_bytes = make_image_bytes("PNG")

    response = client.post(
        f"/api/v1/pets/{pet['id']}/photos",
        headers={"Authorization": f"Bearer {owner_token}"},
        # Uploaded files and normal form values must be sent separately.
        files={
            "image_file": (
                "luna.png",
                image_bytes,
                "image/png",
            )
        },
        data={
            "alt_text": "Luna sitting beside a red ball.",
        },
    )

    assert response.status_code == 201

    response_data = response.json()

    assert response_data["pet_id"] == pet["id"]
    assert response_data["alt_text"] == "Luna sitting beside a red ball."
    assert response_data["sort_order"] == 0

    # The internal MinIO key must not be exposed through the public schema.
    assert "object_key" not in response_data

    # The fake client proves that the route attempted exactly one upload.
    assert len(fake_storage_client.put_calls) == 1
    assert fake_storage_client.put_calls[0]["ContentType"] == "image/png"
    assert fake_storage_client.put_calls[0]["Key"].startswith(f"pets/{pet['id']}/photos/")

    stored_photo = database_session.scalar(
        select(PetPhoto).where(PetPhoto.id == UUID(response_data["id"]))
    )

    assert stored_photo is not None
    assert stored_photo.pet_id == UUID(pet["id"])
    assert stored_photo.object_key == fake_storage_client.put_calls[0]["Key"]


# Intent: verify ordinary shelter staff cannot upload pet photos.
# Ensures: authorization rejects the request before object storage is called.
def test_staff_member_cannot_upload_pet_photo(
    client: TestClient,
    database_session: Session,
    fake_storage_client: FakeObjectStorageClient,
) -> None:
    _, owner_token = register_and_login_for_photo(
        client,
        email="staff-test-owner@example.com",
        display_name="Staff Test Owner",
    )

    shelter = create_shelter_for_photo(client, owner_token)
    pet = create_pet_for_photo(client, owner_token)

    staff_user, staff_token = register_and_login_for_photo(
        client,
        email="photo-staff@example.com",
        display_name="Photo Staff",
    )

    database_session.add(
        ShelterMember(
            shelter_id=UUID(shelter["id"]),
            user_id=UUID(staff_user["id"]),
            role=ShelterMemberRole.STAFF,
        )
    )
    database_session.commit()

    response = client.post(
        f"/api/v1/pets/{pet['id']}/photos",
        headers={"Authorization": f"Bearer {staff_token}"},
        files={
            "image_file": (
                "luna.png",
                make_image_bytes("PNG"),
                "image/png",
            )
        },
        data={"alt_text": "Luna outside."},
    )

    assert response.status_code == 403
    assert response.json() == {"detail": "Shelter owner or manager access is required."}

    # Authorization happens before the file reaches object storage.
    assert fake_storage_client.put_calls == []


# Intent: verify authenticated users without shelter membership cannot upload photos.
# Ensures: the request is rejected before object storage is called.
def test_user_without_shelter_cannot_upload_pet_photo(
    client: TestClient,
    fake_storage_client: FakeObjectStorageClient,
) -> None:
    _, owner_token = register_and_login_for_photo(
        client,
        email="pet-owner@example.com",
        display_name="Pet Owner",
    )

    create_shelter_for_photo(client, owner_token)
    pet = create_pet_for_photo(client, owner_token)

    # This user is authenticated but has no ShelterMember record.
    _, adopter_token = register_and_login_for_photo(
        client,
        email="adopter@example.com",
        display_name="Pet Adopter",
    )

    response = client.post(
        f"/api/v1/pets/{pet['id']}/photos",
        headers={"Authorization": f"Bearer {adopter_token}"},
        files={
            "image_file": (
                "luna.png",
                make_image_bytes("PNG"),
                "image/png",
            )
        },
        data={"alt_text": "Luna outside."},
    )

    assert response.status_code == 403
    assert response.json() == {"detail": "A shelter membership is required."}

    assert fake_storage_client.put_calls == []


# Intent: verify shelter ownership boundaries protect pet-photo uploads.
# Ensures: a shelter cannot upload a photo for another shelter's pet.
def test_shelter_cannot_upload_photo_for_another_shelters_pet(
    client: TestClient,
    fake_storage_client: FakeObjectStorageClient,
) -> None:
    _, first_owner_token = register_and_login_for_photo(
        client,
        email="first-photo-owner@example.com",
        display_name="First Photo Owner",
    )

    create_shelter_for_photo(client, first_owner_token)
    pet = create_pet_for_photo(client, first_owner_token)

    _, second_owner_token = register_and_login_for_photo(
        client,
        email="second-photo-owner@example.com",
        display_name="Second Photo Owner",
    )

    create_shelter_for_photo(
        client,
        second_owner_token,
        name="Dallas Animal Rescue",
        slug="dallas-animal-rescue",
        email="photos@dallasrescue.org",
    )

    response = client.post(
        f"/api/v1/pets/{pet['id']}/photos",
        headers={"Authorization": f"Bearer {second_owner_token}"},
        files={
            "image_file": (
                "luna.png",
                make_image_bytes("PNG"),
                "image/png",
            )
        },
        data={"alt_text": "Luna outside."},
    )

    # The response does not disclose that another shelter owns this pet.
    assert response.status_code == 404
    assert response.json() == {"detail": "Pet not found in your shelter."}

    assert fake_storage_client.put_calls == []


# Intent: verify the upload endpoint rejects corrupted image contents.
# Ensures: invalid image bytes return HTTP 422 without reaching storage.
def test_upload_pet_photo_rejects_corrupted_image(
    client: TestClient,
    fake_storage_client: FakeObjectStorageClient,
) -> None:
    _, owner_token = register_and_login_for_photo(
        client,
        email="invalid-photo-owner@example.com",
        display_name="Invalid Photo Owner",
    )

    create_shelter_for_photo(client, owner_token)
    pet = create_pet_for_photo(client, owner_token)

    response = client.post(
        f"/api/v1/pets/{pet['id']}/photos",
        headers={"Authorization": f"Bearer {owner_token}"},
        files={
            "image_file": (
                "fake-image.png",
                b"This is not an image.",
                "image/png",
            )
        },
        data={"alt_text": "Invalid image."},
    )

    assert response.status_code == 422
    assert response.json() == {"detail": "Upload a valid JPEG, PNG, or WebP image."}

    assert fake_storage_client.put_calls == []


# Intent: verify storage failures are translated into an unavailable response.
# Ensures: the endpoint returns HTTP 503 and does not expose infrastructure details.
def test_upload_pet_photo_returns_503_when_storage_fails(
    client: TestClient,
    fake_storage_client: FakeObjectStorageClient,
) -> None:
    _, owner_token = register_and_login_for_photo(
        client,
        email="storage-failure-owner@example.com",
        display_name="Storage Failure Owner",
    )

    create_shelter_for_photo(client, owner_token)
    pet = create_pet_for_photo(client, owner_token)

    # Configure the fake client to raise the same category of error as boto3.
    fake_storage_client.fail_upload = True

    response = client.post(
        f"/api/v1/pets/{pet['id']}/photos",
        headers={"Authorization": f"Bearer {owner_token}"},
        files={
            "image_file": (
                "luna.webp",
                make_image_bytes("WEBP"),
                "image/webp",
            )
        },
        data={"alt_text": "Luna wearing a blue collar."},
    )

    assert response.status_code == 503
    assert response.json() == {"detail": "Photo storage is temporarily unavailable."}

    assert len(fake_storage_client.put_calls) == 0
