"""create adoption applications

Revision ID: 50d9f71d1bb6
Revises: 77a1ea092fd8
Create Date: 2026-07-26 19:33:52.602504

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "50d9f71d1bb6"
down_revision: str | Sequence[str] | None = "77a1ea092fd8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "adoption_applications",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("pet_id", sa.Uuid(), nullable=False),
        sa.Column("applicant_user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "submitted",
                "reviewing",
                "contacted",
                "approved",
                "rejected",
                "withdrawn",
                name="adoption_application_status",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="draft",
            nullable=False,
        ),
        sa.Column("contact_phone", sa.String(length=30), nullable=True),
        sa.Column("message", sa.Text(), nullable=True),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["applicant_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["pet_id"], ["pets.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "pet_id", "applicant_user_id", name="uq_adoption_applications_pet_applicant"
        ),
    )
    op.create_index(
        "ix_adoption_applications_applicant_status",
        "adoption_applications",
        ["applicant_user_id", "status"],
        unique=False,
    )
    op.create_index(
        "ix_adoption_applications_pet_status",
        "adoption_applications",
        ["pet_id", "status"],
        unique=False,
    )
    op.create_table(
        "application_status_events",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("application_id", sa.Uuid(), nullable=False),
        sa.Column(
            "from_status",
            sa.Enum(
                "draft",
                "submitted",
                "reviewing",
                "contacted",
                "approved",
                "rejected",
                "withdrawn",
                name="application_status_event_from_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=True,
        ),
        sa.Column(
            "to_status",
            sa.Enum(
                "draft",
                "submitted",
                "reviewing",
                "contacted",
                "approved",
                "rejected",
                "withdrawn",
                name="application_status_event_to_status",
                native_enum=False,
                create_constraint=True,
            ),
            nullable=False,
        ),
        sa.Column("changed_by_user_id", sa.Uuid(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["application_id"], ["adoption_applications.id"], ondelete="RESTRICT"
        ),
        sa.ForeignKeyConstraint(["changed_by_user_id"], ["users.id"], ondelete="RESTRICT"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_application_status_events_application_created_at",
        "application_status_events",
        ["application_id", "created_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_application_status_events_application_created_at",
        table_name="application_status_events",
    )
    op.drop_table("application_status_events")
    op.drop_index("ix_adoption_applications_pet_status", table_name="adoption_applications")
    op.drop_index("ix_adoption_applications_applicant_status", table_name="adoption_applications")
    op.drop_table("adoption_applications")
    # ### end Alembic commands ###
