"""create shelter and membership

Revision ID: b42d4134d7c1
Revises: 867ed177127c
Create Date: 2026-07-25 23:54:33.320599

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b42d4134d7c1"
down_revision: str | Sequence[str] | None = "867ed177127c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # create the shelters table with the specified columns and constraints
    op.create_table(
        "shelters",
        sa.Column("id", sa.Uuid(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=160), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("phone", sa.String(length=30), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("char_length(state) = 2", name="ck_shelters_state_length"),
        sa.PrimaryKeyConstraint("id"),
    )

    # create a unique index on the slug column of the shelters table
    #  to ensure that each shelter has a unique slug
    op.create_index(op.f("ix_shelters_slug"), "shelters", ["slug"], unique=True)

    # create the shelter_members table with the specified columns and constraints
    op.create_table(
        "shelter_members",
        sa.Column("shelter_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "owner",
                "manager",
                "staff",
                name="shelter_member_role",
                native_enum=False,
                create_constraint=True,
            ),
            server_default="staff",
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["shelter_id"], ["shelters.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("shelter_id", "user_id"),
        sa.UniqueConstraint("user_id", name="uq_shelter_members_user"),
    )

    # create an index on the shelter_id column of the shelter_members table
    # to optimize queries that filter by shelter_id
    op.create_index(
        op.f("ix_shelter_members_shelter_id"), "shelter_members", ["shelter_id"], unique=False
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_shelter_members_shelter_id"), table_name="shelter_members")
    op.drop_table("shelter_members")
    op.drop_index(op.f("ix_shelters_slug"), table_name="shelters")
    op.drop_table("shelters")
    # ### end Alembic commands ###
